### ISSUE TITLE
My Browser I dos not work

### ISSUE THREAD

**Issue by sebasop320** [ProgrammingHero1/my_cool_browser#3]
when i exetute the python scrtipt in my mac ti says this:
```
Traceback (most recent call last):
  File "/Users/sebastianocampopena/PycharmProjects/browser/main.py", line 5, in <module>
    from PyQt5.QtWebEngineWidgets import *
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

Process finished with exit code 1
``
can sombody help me?

**Comment by faheem-cmd** [comment]
Please install Pyqt5 module.
pip install pyqt5

**Comment by faheem-cmd** [comment]
> when i exetute the python scrtipt in my mac ti says this:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/sebastianocampopena/PycharmProjects/browser/main.py", line 5, in <module>
>     from PyQt5.QtWebEngineWidgets import *
> ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'
> 
> Process finished with exit code 1
> ``
> can sombody help me?
> ```please install pyqt5 module.
pip install pyqt5

**Comment by faheem-cmd** [comment]
> when i exetute the python scrtipt in my mac ti says this:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/sebastianocampopena/PycharmProjects/browser/main.py", line 5, in <module>
>     from PyQt5.QtWebEngineWidgets import *
> ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'
> 
> Process finished with exit code 1
> ``
> can sombody help me?
> ```

Please install pyqt5 module on your project.
pip install pyqt5

**Comment by Prince2347X** [comment]
@sebasop320 @faheem-cmd 
Install it by running 
```
pip install PyQtWebEngine
```
It's also mentioned in the video, you didn't watched it properly lol😂

**Comment by sebasop320** [comment]
> @sebasop320 @faheem-cmd
> Install it by running
> 
> ```
> pip install PyQtWebEngine
> ```
> 
> It's also mentioned in the video, you didn't watched it properly lol😂

Thank You so much
