### ISSUE TITLE
my browser can't go to any urls

### ISSUE THREAD

**Issue by red-socks294** [ProgrammingHero1/my_cool_browser#4]
Hello. When I try to go to any website (e.g github, discord), it just goes to about:blank (i know this to be a blank page). Anyone know how to fix this?

I'm using macOS High Sierra, and Python 3.9. my IDE is pycharm professinal.

anyone know how to fix this?

**Comment by joshua689** [comment]
fel1x0u i can go to github:
i gone into github by typing : https://github.com/

**Comment by red-socks294** [comment]
Well, I can only use google to go to URLs.

**Comment by Codezees** [comment]
Have you tried by reinstalling ?

**Comment by red-socks294** [comment]
Oh. I'll try that tomorrow.
________________________________

**Comment by zoraezimran** [comment]
https://github.com/ProgrammingHero1/my_cool_browser/issues/4#issue-823793583

It depends what type of website you are using because sometimes python doesn't like specific html divisions. 
Only with search engines you will be able to click on urls.

Hope this helps :)

**Comment by Jerry-py** [comment]
need to add https:// when going to website just had this problem
ex: I typed google.com and it is just about:blank
then i typed https://google.com and it works

**Comment by red-socks294** [comment]
Oh, okay.
________________________________

**Comment by red-socks294** [comment]
It works! Thanks, guys!
